resources:
- deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_operator_config.yaml
  name: operator-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/lmiccini/openstack-operator
  newTag: v0.1.20
patches:
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.17-1768031944"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/1", "value":
    {"name": "OPERATOR_IMAGE_URL", "value": "quay.io/lmiccini/openstack-operator:v0.1.17"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.17-1768033026"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.17-1768046406"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.20-1768249975"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/1", "value":
    {"name": "OPERATOR_IMAGE_URL", "value": "quay.io/lmiccini/openstack-operator:v0.1.20"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.20-1768283300"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.20-1768287445"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.20-1768294188"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.20-1768297905"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
- patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "OPENSTACK_RELEASE_VERSION", "value": "0.1.20-1768301149"}}]'
  target:
    kind: Deployment
    name: openstack-operator-controller-operator
    namespace: system
